SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reading](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [varchar](20) NOT NULL,
	[DateTimeUtc] [datetime2](7) NOT NULL,
	[TemperatureInCelcius] [decimal](8, 2) NOT NULL,
	[Humidity] [decimal](8, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Reading] ADD  CONSTRAINT [PK_Reading] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
